version: '3.8'

services:
  generar_bronce:
    build:
      context: ./1-generar_data_bronce
      dockerfile: Dockerfile
    container_name: generar_bronce
    volumes:
      - .:/app # Montamos todo el directorio raíz del proyecto dentro de /app contenedor
    networks:
      - datadriven
    restart: "no"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    depends_on:
      - generar_bronce
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - datadriven

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
      - generar_bronce
    networks:
      - datadriven

  upload_to_hdfs:
    image: bde2020/hadoop-base:2.0.0-hadoop3.2.1-java8
    container_name: upload_to_hdfs
    volumes:
      - .:/app
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    depends_on:
      - namenode
      - datanode
      - generar_bronce
    command:
      - bash
      - /app/1-generar_data_bronce/upload_to_hdfs.sh
    networks:
      - datadriven

  pyspark-job:
    build:
      context: ./2-pyspark_plata
      dockerfile: Dockerfile
    user: "0:0"
    container_name: pyspark_plata
    volumes:
      - ./2-pyspark_plata:/app
    environment:
      HADOOP_USER_NAME: root
      USER: root
      LOGNAME: root
      JAVA_TOOL_OPTIONS: -Duser.name=root
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USERNAME: admin
      MONGO_PASSWORD: password
      MONGO_DB: bank_db
      MONGO_COLLECTION: solicitudes
    depends_on:
      upload_to_hdfs:
        condition: service_completed_successfully
      mongodb:
        condition: service_started
    networks:
      - datadriven
    restart: "no"

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    depends_on:
      - generar_bronce
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=data_driven_cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=3
      - HDFS_CONF_dfs_namenode_heartbeat_recheck_interval=2500
      - HDFS_CONF_dfs_heartbeat_interval=1
    networks:
      - datadriven

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=data_driven_cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_datanode_data_dir=file:///hadoop/dfs/data
    depends_on:
      - namenode
      - generar_bronce
    networks:
      - datadriven

  motor:
    build:
      context: ./3-motor_aplicacion
      dockerfile: Dockerfile
    container_name: motor
    volumes:
      - .:/app # Montamos todo el directorio raíz del proyecto dentro de /app contenedor
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USERNAME: admin
      MONGO_PASSWORD: password
      MONGO_DB: bank_db
      MONGO_COLLECTION: solicitudes
    depends_on:
      mongodb:
        condition: service_started
      generar_bronce:
        condition: service_completed_successfully
      upload_to_hdfs:
        condition: service_completed_successfully
      pyspark-job:
        condition: service_completed_successfully
    networks:
      - datadriven

  api_motor_nuevo:
    build:
      context: ./5-API_MOTOR
      dockerfile: Dockerfile
    container_name: api_motor_nuevo
    ports:
      - "8000:8000"
    volumes:
      - ./5-API_MOTOR:/app # Mapeo clave para leer el .pkl localmente y reflejar los JSON creados
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USERNAME: admin
      MONGO_PASSWORD: password
      MONGO_DB: bank_db
      MONGO_COLLECTION: solicitudes
    depends_on:
      mongodb:
        condition: service_started
      pyspark-job:
        condition: service_completed_successfully
    networks:
      - datadriven

volumes:
  mongodb_data:

networks:
  datadriven:
    driver: bridge